title: A Cecília está on!
description: Assista a Cecília crescendo enquanto dorme
logo: /pics/sleeping_with_dady2.jpg
connection_to:
  baby_cam: https://selfish-moth-66.loca.lt
theme: jekyll-theme-minimal
