title: A Cecília está on!
description: Assista à Cecília crescendo enquanto dorme!
logo: /pics/sleeping_with_dady2.jpg
connection_to:
  baby_cam: https://blue-seahorse-80.loca.lt
theme: jekyll-theme-minimal
